import {useEffect,useState} from 'react';import {api} from '../api';import {Link} from 'react-router-dom';import {t} from '../i18n';
const COURSES=[{id:1,t:'Fractions & Number Sense',n:'Foundation'},{id:2,t:'Algebra Fundamentals',n:'Intermediate'},{id:3,t:'Equations',n:'Advanced'},{id:4,t:'Aptitude & Interview Prep',n:'Career'}];
export default function Dashboard({me,setMe}){
 const [lb,setLb]=useState([]);const [err,setErr]=useState('');useEffect(()=>{api('/leaderboard').then(setLb)},[me]);
 const s=me.state,o=me.overall;const unlock=async id=>{try{setMe(await api('/unlock',{id}));setErr('')}catch(e){setErr(e.message)}};
 const weak=[...me.graph].filter(n=>s.unlocked.includes(n.course)&&n.mastery>0).sort((a,b)=>a.mastery-b.mastery)[0]?.course||1;const cp=id=>{const v=me.graph.filter(n=>n.course===id&&n.mastery>0);return v.length?Math.round(v.reduce((a,n)=>a+n.mastery,0)/v.length)+'% mastery':'not started'};const rec=s.history.filter(h=>h.retest&&h.correct&&h.diag.reasoningOk).length;
 const S=(v,l)=><div className="card stat"><div><div className="big">{v}</div><small>{l}</small></div></div>;
 const emp=s.track==='employee',cc=emp?4:1;const tasks=[{n:emp?'Lesson - Percentages & Ratios':'Lesson 1 - Understanding Fractions',m:'Lesson · 10 min',d:s.done.includes('l'+cc),to:'/learn?course='+cc},{n:emp?'Quiz, coaching & retest: Aptitude':'Quiz, coaching & retest: Fraction Addition',m:'Practice · 12 min',d:rec>0,to:'/learn?course='+cc}];
 return <div><div className="grid">{S(s.done.length,t('les'))}{S(o+'%',t('ov'))}{S(s.history.length,t('att'))}{S(rec,'Misconceptions recovered')}{S(Math.round(s.minutes||0)+' min','Meaningful time')}</div>
 <div className="cols"><div>
  <div className="card"><h3>{t('tasks')} <span className="tag">{s.tasks%2}/2 = +100 coins</span></h3>{tasks.map(k=><div className="row" key={k.n}><div><b>{k.n}</b><br/><small>{k.m}</small></div>{k.d?<span className="tag g">Done</span>:<Link className="btn" to={k.to}>{t('start')} →</Link>}</div>)}</div>
  <div className="card"><h3>{t('crs')}</h3>{COURSES.filter(c=>s.track!=='employee'||c.id===4).map(c=><div className="row" key={c.id}><div><b>{c.t}</b><br/><small>{c.n} · {cp(c.id)}</small></div>{s.unlocked.includes(c.id)?<Link className="btn" to={'/learn?course='+c.id}>{c.id===1?'Continue':'Start'} →</Link>:<button className="gold" style={{width:'auto'}} onClick={()=>unlock(c.id)}>Unlock (80% or 1000 coins)</button>}</div>)}<p className="warn">{err}</p>{err&&<Link className="btn" to={'/learn?course='+weak}>Targeted practice on weak area →</Link>}</div>
  <div className="card"><h3>{t('act')}</h3>{s.history.slice(-4).reverse().map((h,i)=><div className="row" key={i}><span>{h.retest?'Retest':'Quiz'}: {h.correct?'answer correct':'answer incorrect'}</span><span className="tag">{h.diag.label}</span></div>)}{!s.history.length&&<small>No activity yet</small>}</div></div>
 <div><div className="card"><h3 style={{textAlign:'center'}}>Overall Mastery</h3><svg className="ring" width="150" height="150" viewBox="0 0 150 150"><circle cx="75" cy="75" r="60" fill="none" stroke="#2a2210" strokeWidth="14"/><circle cx="75" cy="75" r="60" fill="none" stroke="#d4af37" strokeWidth="14" strokeLinecap="round" strokeDasharray={`${o*3.77} 377`} transform="rotate(-90 75 75)"/><text x="75" y="82" textAnchor="middle" fill="#f5f0e1" fontSize="28" fontWeight="700">{o}%</text></svg>
   <p style={{textAlign:'center'}}><small>{s.mastery&&Object.values(me.graph).filter(n=>n.status==='weak'||n.status==='repeated').length} topics need recovery</small></p><Link className="btn" style={{display:'block',textAlign:'center'}} to="/map">View Learning Gaps →</Link></div>
  <div className="card"><h3>{t('coins')}</h3><div className="big" style={{color:'#f59e0b'}}>{me.user.coins}</div><small>2 tasks/day = 100 coins. 1000 coins unlock a course.</small></div>
  <div className="card"><h3>{t('lb')}</h3>{lb.map((u,i)=><p key={i}>{i+1}. {u.name} · {u.overall}% · {u.coins} coins</p>)}</div></div></div></div>}